<h3>Question (ID-3083235):</h3><h2>Problem with unzipping file</h2><p>I have two zip files, both of them open well with Windows Explorer and 7-zip. </p>

<p>However when i open them with Python's zipfile module [ zipfile.ZipFile("filex.zip") ], one of them gets opened but the other one gives error "BadZipfile: File is not a zip file".</p>

<p>I've made sure that the latter one is a valid Zip File by opening it with 7-Zip and looking at its properties (says 7Zip.ZIP). When I open the file with a text editor, the first two characters are "PK", showing that it is indeed a zip file.</p>

<p>I'm using Python 2.5 and really don't have any clue how to go about for this. I've tried it both with Windows as well as Ubuntu and problem exists on both platforms.</p>

<p><strong>Update:</strong> Traceback from Python 2.5.4 on Windows:</p>

<pre><code>Traceback (most recent call last):
File "&lt;module1&gt;", line 5, in &lt;module&gt;
    zipfile.ZipFile("c:/temp/test.zip")
File "C:\Python25\lib\zipfile.py", line 346, in init
    self._GetContents()
File "C:\Python25\lib\zipfile.py", line 366, in _GetContents
    self._RealGetContents()
File "C:\Python25\lib\zipfile.py", line 378, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
</code></pre>

<p>Basically when the _EndRecData function is called for getting data from End of Central Directory" record, the comment length checkout fails [ endrec[7] == len(comment) ]. </p>

<p>The values of locals in the _EndRecData function are as following:</p>

<p>END_BLOCK: 4096,
 comment: '\x00',
 data: '\xd6\xf6\x03\x00\x88,N8?,
 start: 4073</p>
<br /><h3>Answers (Total-6):</h3><b>#0</b><br /><p>try to run unix <code>file</code> command on both of your files. may be it will give you some clue</p>
<br /><b>#1</b><br /><p>Show the full traceback that you got from Python -- this may give a hint as to what the specific problem is. <strong>Unanswered:</strong> What software produced the bad file, and on what platform?</p>

<p>Update: Traceback indicates having problem detecting the "End of Central Directory" record in the file -- see function _EndRecData starting at line 128 of C:\Python25\Lib\zipfile.py</p>

<p>Suggestions:<br>
(1) Trace through the above function<br>
(2) Try it on the latest Python<br>
(3) Answer the question above.<br>
(4) Read <a href="http://www.velocityreviews.com/forums/t658579-badzipfile-file-is-not-a-zip-file.html" rel="nofollow">this</a> and anything else found by <code>google("BadZipfile: File is not a zip file")</code> that appears to be relevant</p>
<br /><b>#2</b><br /><p>I had the same problem and was able to solve this issue for my files, see my answer at 
<a href="http://stackoverflow.com/questions/4923142/zipfile-cant-handle-some-type-of-zip-data">zipfile cant handle some type of zip data?</a></p>
<br /><b>#3</b><br /><p>Are you the one that compressed both files? I'd recommend recompressing the "bad" file with normal compression method without any fancy options that Python might not recognize.</p>
<br /><b>#4</b><br /><p>Along with <code>file</code> on Unix/Linux as zed says, have a look at what <code>mimetype.guess_type(filename)</code> says about the offending file, and all other functions in mimetype have to say about that file.</p>
<br /><b>#5</b><br /><p>Have you tried a newer python, or if that is too much trouble, simply a newer zipfile.py? I have successfully used a copy of zipfile.py from Python 2.6.2 (latest at the time) with Python 2.5 in order to open some zip files that weren't supported by Py2.5s zipfile module.</p>
<br />