<h3>Question (ID-739191):</h3><h2>"ImportError: No module named dummy" on fresh Django project</h2><p>I've got the following installed through MacPorts on MacOS X 10.5.6:</p>

<pre><code>py25-sqlite3 @2.5.4_0 (active)
python25 @2.5.4_1+darwin_9+macosx (active)
sqlite3 @3.6.12_0 (active)
</code></pre>

<p><code>python25</code> is correctly set as my system's default Python.</p>

<p>I downloaded a fresh copy of Django 1.1 beta (I have the same problem with 1.0 and trunk, though) and installed it with "<code>sudo python setup.py install</code>".</p>

<p>Things seem to load correctly through the interactive interpreter:</p>

<pre><code>$ python
Python 2.5.4 (r254:67916, Apr 10 2009, 16:02:52) 
[GCC 4.0.1 (Apple Inc. build 5490)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
&gt;&gt;&gt; import django
&gt;&gt;&gt; import sqlite3
&gt;&gt;&gt; ^D
</code></pre>

<p>But:</p>

<pre><code>$ django-admin.py startproject foo
$ cd foo/
$ python manage.py runserver
Validating models...
Unhandled exception in thread started by &lt;function inner_run at 0x6c1e70&gt;
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/django/core/management/commands/runserver.py", line 48, in inner_run
    self.validate(display_num_errors=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/django/core/management/base.py", line 246, in validate
    num_errors = get_validation_errors(s, app)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/django/core/management/validation.py", line 22, in get_validation_errors
    from django.db import models, connection
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/django/db/__init__.py", line 22, in &lt;module&gt;
    backend = __import__('%s.base' % settings.DATABASE_ENGINE, {}, {}, [''])
ImportError: No module named dummy.base
</code></pre>

<p>If I change <code>DATABASE_ENGINE</code> in <code>settings.py</code> to "<code>sqlite3</code>", I get the following, seemingly related problem:</p>

<pre><code>$ python manage.py runserver

Validating models...
Unhandled exception in thread started by &lt;function inner_run at 0x6c1e70&gt;
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/django/core/management/commands/runserver.py", line 48, in inner_run
    self.validate(display_num_errors=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/django/core/management/base.py", line 246, in validate
    num_errors = get_validation_errors(s, app)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/django/core/management/validation.py", line 22, in get_validation_errors
    from django.db import models, connection
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/django/db/__init__.py", line 22, in &lt;module&gt;
    backend = __import__('%s.base' % settings.DATABASE_ENGINE, {}, {}, [''])
ImportError: No module named base
^C$
</code></pre>

<p>I swear this all worked a few days ago and I don't recall changing anything related to Django or Python, installation-wise.</p>

<p>My various Google adventures have turned up nothing useful. So... Any ideas?</p>

<p>Edit: '<code>syncdb</code>' raises the same exceptions.</p>
<br /><h3>Answers (Total-7):</h3><b>#0</b><br /><p>I found this <a href="http://groups.google.com/group/django-users/browse%5Fthread/thread/ea60854ad2e00b98" rel="nofollow">thread</a> on the Django Users group:</p>

<p>They suggest that it has something to do with the way MacPorts installs Python. I wish I had more details to help you with, but as a workaround, I recommend you use MacPorts to uninstall this copy of Python and try to use alternate method of install it. If you're looking for an quick and easy install, you might want to try <a href="http://wiki.python.org/moin/MacPython/Leopard" rel="nofollow">MacPython</a>. Hope this helps!</p>
<br /><b>#1</b><br /><p>did you try the intro doc? <a href="http://docs.djangoproject.com/en/dev/intro/tutorial01" rel="nofollow">doc link</a></p>

<p>If you follow this doc, you can at least say, "at step XXXX it got error YYY".  Then someone with some experience (no me) should be able to find a good answer.  This link is for the trunk, there's a link for 1.0 docs at the top.</p>
<br /><b>#2</b><br /><p>duh, i'm not thinking.  Just run</p>

<pre><code>python manage.py syncdb
</code></pre>

<p>this will build you db so you can then run the server.</p>
<br /><b>#3</b><br /><p>Re-check your settings.py.  In the second case, it looks like your DATABASE_ENGINE is set to the empty string, not 'sqlite3'.</p>
<br /><b>#4</b><br /><p>This isn't an answer, exactly, but I would try removing the MacPorts install of Django and start over. Then try adding <a href="http://peak.telecommunity.com/DevCenter/EasyInstall" rel="nofollow">easy_install</a> and using that to install everything. To make things cleaner and easier to start over, you might also want to add <a href="http://pypi.python.org/pypi/virtualenv" rel="nofollow">virtualenv</a>, which lets you set up multiple self-contained Python environments.</p>
<br /><b>#5</b><br /><p>You can also try installing the py25-hashlib package if you don't have it already. I found this described on the <a href="http://code.djangoproject.com/ticket/8489" rel="nofollow">django bug tracking site</a>.</p>

<p>Normally, this package is part of python, but it's either missing or wrong in the macports version, from what I've read.</p>

<p>I found more info on the macports version of py25-hashlib <a href="http://py25-hashlib.darwinports.com/" rel="nofollow">here</a>.</p>
<br /><b>#6</b><br /><p>Try using the full path to python as well as checking the module path</p>
<br />