<h3>Question (ID-7379596):</h3><h2>creepy design in python</h2><p>can somebody help me with the following piece of the code:</p>

<pre><code>try:
    #do some things
    myClass.close()
except Exception, error:
    myClass.close()
    raise error
</code></pre>

<p>as You see I can't use here <code>finally</code> because in that case I will not know if an error actually occured, and I need to raise this error (raise error)</p>

<p>my question is how can I avoid using this two times <code>myClass.close()?</code> thanks in advance for any help</p>
<br /><h3>Answers (Total-6):</h3><b>#0</b><br /><p>You can use <code>finally</code> :)</p>

<p>This should do what you want:</p>

<pre><code>try:
    #do some things
finally:
    myClass.close()
</code></pre>
<br /><b>#1</b><br /><p>You can chain <code>try</code>, <code>except</code> and <code>finally</code> <a href="http://docs.python.org/reference/compound_stmts.html#the-try-statement" rel="nofollow">since Python 2.5</a>:</p>

<pre><code>try:
    # Do some things...
    pass
except Exception, error:
    # Log the error...
    raise
finally:
    myClass.close()
</code></pre>
<br /><b>#2</b><br /><p>This is equivalent to your code:</p>

<pre><code>try:
    #do some things
finally:
    myClass.close()
</code></pre>

<p>First it calls <code>myClass.close()</code> and if there was a error it is raised again.</p>

<p>You can also have this to handle specific exceptions:</p>

<pre><code>try:
    #do some things
except Exception, error:
    raise # re-raise the original exception
finally:
    myClass.close()
</code></pre>
<br /><b>#3</b><br /><p>Next to a finally (that would work) you could also use a context manager that calls your myClass.close() method on exit.</p>
<br /><b>#4</b><br /><p>Nest it.</p>

<pre><code>try:
  try:
    ...
  except ...:
    raise error
finally:
  myClass.close()
</code></pre>
<br /><b>#5</b><br /><p>Regardless this will not work.
If you already raised an exception/error the first time you invoked myClass.close(), calling it again will be of no help.
The error handling keywords are for implementing fallbacks, reporting and routing of the error-flow.</p>

<p>See here for error handling:
<a href="http://stackoverflow.com/questions/1611561/python-error-handling-with-try-finally">Python Error Handling with try/finally</a></p>
<br />