<h3>Question (ID-8146386):</h3><h2>Python - Conditionally Catching Exceptions</h2><p>Is it possible to conditionally catch exceptions in python? I would like to be able to write a function so that the caller can decide who handles the exception. </p>

<p>Basically, I would like something like this:</p>

<pre><code>def my_func(my_arg, handle_exceptions):
    try:
        do_something(my_arg)
    except Exception, e if handle_exceptions:
        print "my_func is handling the exception"
</code></pre>

<p>I know I could write some kludgy code that does what I want, but I want a pythonic answer if there is one.<br>
Thanks.</p>
<br /><h3>Answers (Total-7):</h3><b>#0</b><br /><p>You can re-raise the exception if you don't want to handle it:</p>

<pre><code>def my_func(my_arg, handle_exceptions):
    try:
        do_something(my_arg)
    except Exception, e:
        if not handle_exceptions:
            # preserve prior stack trace
            raise

            # Or, if you dont care about the stack prior to this point
            #raise Exception(e)

            # similarly, you can just re-raise e.  The stack trace will start here though.
            #raise e
        else:
            print "my_func is handling the exception"
</code></pre>

<hr>

<p>Another option is to create your own exceptions that subclass <code>Exception</code> (or a specific exception like <code>urllib2.HTTPError</code>) and then only catch/throw (<code>raise</code>) your custom exception:</p>

<pre><code>class MyException(Exception):
    def __init__(self, message):
        self.message = message

class MyExceptionTwo(Exception):
    def __init__(self, message):
        self.message = message
    def __repr__(self):
        return "Hi, I'm MyExceptionTwo.  My error message is: %s" % self.message

def something():
    if not tuesday:
        raise MyException("Error: it's not Tuesday.")
    else:
        raise MyExceptionTwo("Error: it's Tuesday.")

def my_func(my_arg):
    try:
        something()
    except MyException, e:
        print e.message
    # Will pass MyExceptionTwo up the call chain

def my_other_func():
    try:
        my_func(your_arg)
    except MyExceptionTwo, e:
        print str(e)
    # No need to catch MyException here since we know my_func() handles it
    # but we can hadle MyExceptionTwo here
</code></pre>
<br /><b>#1</b><br /><p>You can use:</p>

<pre><code>def my_func(my_arg, handle_exceptions):
  try:
    do_something(my_arg);
  except Exception as e:
    if not handle_exceptions: raise
    print "my_func is handling the exception";
</code></pre>
<br /><b>#2</b><br /><p>The exception type can be a variable.</p>

<pre><code>def my_func(my_arg, handle_exceptions):
  if handle_exceptions:
    exc_type = Exception
  else:
    exc_type = None

  try:
    do_something(my_arg);
  except exc_type, e:
    print "my_func is handling the exception";
</code></pre>

<p>Obfuscated Python ("Pythonic"?) version:</p>

<pre><code>def my_func(my_arg, handle_exceptions):
  try:
    do_something(my_arg);
  except (handle_exceptions and Exception), e:
    print "my_func is handling the exception";
</code></pre>

<p>Works without the parentheses, actually, but as long as we're being obfuscated let's not confuse people with little known rules like precedence for except statements.</p>
<br /><b>#3</b><br /><p>You could always catch it and conditionally re-raise it like so:</p>

<pre><code>def my_func(my_arg, handle_exceptions):
  try:
    do_something(my_arg)
  except Exception:
    if handle_exceptions:
      print "my_func is handling the exception"
      #handle it
    else: 
      print "my_func is NOT handling the exception"
      raise
</code></pre>
<br /><b>#4</b><br /><p>Yes.  I prefer positive conditions when it makes sense:</p>

<pre><code>def my_func(my_arg, handle_exceptions):
  try:
    do_something(my_arg);
  except Exception, e:
    if handle_exceptions:
        print "my_func is handling the exception"
    else:
        raise
</code></pre>
<br /><b>#5</b><br /><p>The question just doesn't have enough answers ;-)</p>

<p>Here's one more for the record books.  Just create a dummy exception:</p>

<pre><code>class NeverMatch(Exception):
    'An exception class that is never raised by any code anywhere'
</code></pre>

<p>Then, use a conditional expression to decide whether to match the real exception or the placeholder exception (which never gets raised):</p>

<pre><code>try:
    do_something(my_arg)
except (Exception if handle_exceptions else NeverMatch) as e:
    print 'I am handling it'
</code></pre>
<br /><b>#6</b><br /><p>You have a two basic choices:</p>

<ol>
<li>Treat <code>handle_exceptions</code> as a boolean, and re-raise if <code>False</code></li>
<li>Treat <code>handle_exceptions</code> as the exceptions to handle</li>
</ol>

<p>Along the boolean route you have two basic choices:</p>

<pre><code>def my_func(my_arg, handle_exceptions):
    try:
        do_something(my_arg)
    except Exception, e:
        if not handle_exceptions:
            raise
        print "my_func is handling the exception"
</code></pre>

<p>or</p>

<pre><code>def my_func(my_arg, handle_exceptions):
    if handle_exceptions:
        exceptions = ValueError, IndexError # or whatever
    else:
        exceptions = NoExceptions # None in 2.x, or custom Exception class in 3.x
    try:
        do_something(my_arg)
    except exceptions, e:
        print "my_func is handling the exception"
</code></pre>

<p>Along the 'treat <code>handle_exceptions</code> as the exceptions to handle' route you can do this:</p>

<pre><code>class NoExceptions(Exception):
    'Dummy exception, never raised'

def my_func(my_arg, handle_exceptions=NoExceptions):
    try:
        do_something(my_arg)
    except handle_exceptions, e:
        print "my_func is handling the exception"
</code></pre>

<p>and you would call it like so:</p>

<pre><code>my_func(some_arg, ValueError)  # to handle ValueErrors
</code></pre>

<p>or</p>

<pre><code>my_func(some_arg)  # to not handle any exeptions
</code></pre>

<p>This has the advantage/disadvantage of the caller being able to specify which exceptions are handled.  If you do take this last route you might also want to specify an exception handler, perhaps something like this:</p>

<pre><code>def my_func(my_arg, handle_exceptions=NoExceptions, handler=None):
    try:
        do_something(my_arg)
    except handle_exceptions, e:
        if handler is not None:
            handler(e)
        else:
            log_this_exception()
</code></pre>
<br />