[{"text": ["Python Ignore Exception and Go Back to Where I Was"], "childNum": 0, "tag": "h2", "senID": 0, "childList": []}, {"text": ["I know using below code to ignore a certain exception, but how to let the code go back to where it got exception and keep executing?", "Say if the exception 'Exception' raises in do_something1, how to make the code ignore it and keep finishing do_something1 and process do_something2?", "My code just go to finally block after process pass in except block.", "Please advise, thanks."], "childNum": 0, "tag": "p", "senID": 1, "childList": []}, {"code": "<pre>\n<code>\n try:\n    do_something1\n    do_something2\n    do_something3\n    do_something4\nexcept Exception:\n    pass\nfinally:\n    clean_up\n</code>\n</pre>\n", "senID": 2}, {"text": ["EDIT:\nThanks for the reply.", "Now I know what's the correct way to do it.", "But here's another question, can I just ignore a specific exception (say if I know the error number).", "Is below code possible?"], "childNum": 1, "tag": "p", "senID": 3, "childList": [{"text": "EDIT:", "childNum": 0, "tag": "strong", "pos": 0, "childList": []}]}, {"code": "<pre>\n<code>\n try:\n    do_something1\nexcept Exception.strerror == 10001:\n    pass\n\ntry:\n    do_something2\nexcept Exception.strerror == 10002:\n    pass\nfinally:\n    clean_up\n\ndo_something3\ndo_something4\n</code>\n</pre>\n", "senID": 4}]