[{"text": ["Python: Convert Unicode to ASCII without errors"], "childNum": 0, "tag": "h2", "senID": 0, "childList": []}, {"code": "<pre>\n<code>\n html = urllib.urlopen(link).read()\nhtml.encode(\"utf8\",\"ignore\")\nself.response.out.write(html)\n</code>\n</pre>\n", "senID": 1}, {"code": "<pre>\n<code>\n Traceback (most recent call last):\n  File \"/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/webapp/__init__.py\", line 507, in __call__\n    handler.get(*groups)\n  File \"/Users/greg/clounce/main.py\", line 55, in get\n    html.encode(\"utf8\",\"ignore\")\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xa0 in position 2818: ordinal not in range(128)\n</code>\n</pre>\n", "senID": 2}]