Question (ID-1383126): Django/Python Beginner: Error when executing python manage.py syncdb - psycopg2 not found I have Pythong2.6, psycopg2 and pgAdmin3 installed using Macports. My settings.py is: 

 DATABASE_ENGINE = 'postgresql_psycopg2'   # 'postgresql_psycopg2', 'postgresql', 'mysql', 'sqlite3' or 'oracle'.
DATABASE_NAME = 'mysite'    # Or path to database file if using sqlite3.
DATABASE_USER = 'postgres'    # Not used with sqlite3.
DATABASE_PASSWORD = ''   # Not used with sqlite3.
DATABASE_HOST = ''    # Set to empty string for localhost. Not used with sqlite3.
DATABASE_PORT = ''    # Set to empty string for default. Not used with sqlite3.
 

 The error I get when I run python manage.py syncdb is: 

 Traceback (most recent call last):
 File "manage.py", line 11, in &lt;module&gt;
 execute_manager(settings)
 File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/core/management/__init__.py", line 362, in execute_manager
 utility.execute()
 File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/core/management/__init__.py", line 303, in execute
 self.fetch_command(subcommand).run_from_argv(self.argv)
 File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/core/management/base.py", line 195, in run_from_argv
 self.execute(*args, **options.__dict__)
 File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/core/management/base.py", line 221, in execute
 self.validate()
 File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/core/management/base.py", line 249, in validate
 num_errors = get_validation_errors(s, app)
 File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/core/management/validation.py", line 22, in get_validation_errors
 from django.db import models, connection
 File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/db/__init__.py", line 41, in &lt;module&gt;
 backend = load_backend(settings.DATABASE_ENGINE)
 File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/db/__init__.py", line 17, in load_backend
 return import_module('.base', 'django.db.backends.%s' % backend_name)
 File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/utils/importlib.py", line 35, in import_module
 __import__(name)
 File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 22, in &lt;module&gt;
 raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named psycopg2
 

 Please note, I am a complete beginner in this stuff. I am originally a PHP-guy and trying out Python for a small personal project. Do I need to "turn on" Postgres? 

 Also, when I sudo python manage.py runserver 8080
I get this error: 

 Validating models...
Unhandled exception in thread started by &lt;function inner_run at 0x1242670&gt;
Traceback (most recent call last):
 File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/core/management/commands/runserver.py", line 48, in inner_run
 self.validate(display_num_errors=True)
 File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/core/management/base.py", line 249, in validate
 num_errors = get_validation_errors(s, app)
 File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/core/management/validation.py", line 22, in get_validation_errors
 from django.db import models, connection
 File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/db/__init__.py", line 41, in &lt;module&gt;
 backend = load_backend(settings.DATABASE_ENGINE)
 File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/db/__init__.py", line 17, in load_backend
 return import_module('.base', 'django.db.backends.%s' % backend_name)
 File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/utils/importlib.py", line 35, in import_module
 __import__(name)
 File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 22, in &lt;module&gt;
 raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: No module named psycopg2
 

 Please guide me. Any reply will be appreciated. 

 Thanks, 

 Wenbert! 
 Answers (Total-6): #0 There seems to be a problem with your psycopg2 installation â€“ Python does not find it. This is a Python installation problem, not a Django issue. 

 You can try to load it manually using the Python interpreter and see if it works: 

 $ python
&gt;&gt;&gt; import psycopg2
 

 If you get an ImportError exception, your installation is erroneous. To get a list of all directories Python looks for modules, use sys.path : 

 $ python
&gt;&gt;&gt; import sys
&gt;&gt;&gt; print sys.path
 

 You can also add custom directories to Python's module search path by modifying the sys.path variable. Do this somewhere before the respective import statement(s): 

 import sys
sys.path.append("my-path")

# ...
import psycopg2
 
 #1 Although you installed it, Python can apparently not find the module psycopg2. This is usually due to the module not being in Python's path. See if you can find a folder named psycopg2 in /Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages . If it's not there, did MacPorts tell you where it put psycopg2? If you can locate it, just move it to the site-packages directory and you should be fine. 
 #2 For the record I got the same error for a different reason: 

 I had put 

 'ENGINE': 'django.db.backends.postgresql'
 

 instead of 

 'ENGINE': 'django.db.backends.postgresql_psycopg2'
 

 in settings.py 
 #3 Tim's answer worked for me too. 
By default, settings.py shows options like 'postgresql_psycopg2', 'mysql', etc, without a package name. Prefixing with 'django.db.backends.' worked for me (for postgresql_psycopg2, at least). 
 #4 Yes Tim's answer works for me too.It works without prefix 'django.db.backends.' also. But remember to create database or schema you mentioned in settings.py: 

 DATABASE_NAME = 'your_db_name' 
 

 manually using your database client so when you run 'python manage.py syncdb' you don't get the same problem. I was stuck because i didn't create it manually. I got the same problem may be because I used buildout. 
 #5 I got the same error, but it was because I was using python26 ./manage.py runserver when my virtualenv only had python and python2.6 executables (thus the system python26 was being used, which didn't have psycopg2 installed