<h3>Question (ID-944592):</h3><h2>Best practice for Python Assert</h2><p>Is there a performance or code maintenance issue with using assert as part of the standard code instead of using it just for debugging purposes?</p>

<p>Is</p>

<pre><code>assert x &gt;= 0, 'x is less then zero'
</code></pre>

<p>and better or worse then </p>

<pre><code>if x &lt; 0:
    raise Exception, 'x is less then zero'
</code></pre>

<p>Also, is there anyway to set a business rule like <code>if x &lt; 0 raise error</code> that is always checked with out the try, except, finally so, if at anytime throughout the code x is &lt; 0 an error is raised, like if you set <code>assert x &lt; 0</code> at the start of a function, anywhere within the function where x becomes less then 0 an exception is raised?</p>
<br /><h3>Answers (Total-6):</h3><b>#0</b><br /><p>Asserts should be used to test conditions that <em>should never happen</em>.  The purpose is to crash early in the case of a corrupt program state.</p>

<p>Exceptions should be used for errors that can conceivably happen, and you should almost always create your own Exception classes.</p>

<p><hr /></p>

<p>For example, if you're writing a function to read from a configuration file into a <code>dict</code>, improper formatting in the file should raise a <code>ConfigurationSyntaxError</code>, while you can <code>assert</code> that you're not about to return <code>None</code>.</p>

<p><hr /></p>

<p>In your example, if <code>x</code> is a value set via a user interface or from an external source, an exception is best.</p>

<p>If <code>x</code> is only set by your own code in the same program, go with an assertion.</p>
<br /><b>#1</b><br /><p>To be able to automatically throw an error when x become less than zero throughout the function. You can use <a href="http://docs.python.org/reference/datamodel.html#implementing-descriptors" rel="nofollow">class descriptors</a>. Here is an example:</p>

<pre><code>class ZeroException(Exception):
    pass

class variable(object):
    def __init__(self, value=0):
        self.__x = value

    def __set__(self, obj, value):
        if value &lt; 0:
            raise ZeroException('x is less than zero')

        self.__x  = value

    def __get__(self, obj, objType):
        return self.__x

class MyClass(object):
    x = variable()

&gt;&gt;&gt; m = MyClass()
&gt;&gt;&gt; m.x = 10
&gt;&gt;&gt; m.x -= 20
Traceback (most recent call last):
  File "&lt;stdin&gt;", line 1, in &lt;module&gt;
  File "my.py", line 7, in __set__
    raise ZeroException('x is less than zero')
ZeroException: x is less than zero
</code></pre>
<br /><b>#2</b><br /><p><strong>"assert" statements are removed when the compilation is optimized</strong>.  So, yes, there are both performance and functional differences.</p>

<blockquote>
  <p>The current code generator emits no code for an assert statement when optimization is requested at compile time. - <a href="http://docs.python.org/reference/simple_stmts.html#the-assert-statement" rel="nofollow">Python 2.6.4 Docs</a></p>
</blockquote>

<p>If you use <code>assert</code> to implement application functionality, then optimize the deployment to production, you will be plagued by "but-it-works-in-dev" defects.</p>

<p>See <a href="http://docs.python.org/using/cmdline.html?highlight=optimization%20options#envvar-PYTHONOPTIMIZE" rel="nofollow">PYTHONOPTIMIZE</a> and <a href="http://docs.python.org/using/cmdline.html?highlight=optimization%20options#miscellaneous-options" rel="nofollow">-O -OO</a></p>
<br /><b>#3</b><br /><p>The only thing that's really wrong with this approach is that it's hard to make a very descriptive exception using assert statements.  If you're looking for the simpler syntax, remember you <em>can</em> also do something like this:</p>

<pre><code>class XLessThanZeroException(Exception):
    pass

def CheckX(x):
    if x &lt; 0:
        raise XLessThanZeroException()

def foo(x):
    CheckX(x)
    #do stuff here
</code></pre>

<p>Another problem is that using assert for normal condition-checking is that it makes it difficult to disable the debugging asserts using the -O flag.</p>
<br /><b>#4</b><br /><p>In addition to the other answers, asserts themselves throw exceptions, but only AssertionErrors. From a utilitarian standpoint, assertions aren't suitable for when you need fine grain control over which exceptions you catch.</p>
<br /><b>#5</b><br /><p>Well, in general I agree with Deestan, but sometimes we need to test our custom exception, so...</p>

<p>we can take unittest's method assertRaises, rewrite it a little - and get asserNotRaises method:</p>

<pre><code>class SomeTest(unittest.TestCase):
    def assertNotRaises(self, excClass, callableObj, *args, **kwargs):
        try:
            callableObj(*args, **kwargs)
        except excClass:
            if hasattr(excClass,'__name__'): excName = excClass.__name__
            else: excName = str(excClass)
            raise self.failureException, "%s raised" % excName
</code></pre>

<p>And then to use it like this:</p>

<pre><code>self.assertNotRaises(MyException, my_callable)
</code></pre>
<br />