[[{"text": ["You can use idle -n to avoid such issues (albeit possibly getting some other limitations)."], "childNum": 1, "tag": "p", "senID": 0, "childList": [{"text": "idle -n", "childNum": 0, "tag": "code", "pos": 0, "childList": []}]}], [{"text": ["In Python 3.0.1, I have gotten that error after I Ctrl-C to interrupt a previous run of a program in Idle's Python Shell and then try to run a script."], "childNum": 0, "tag": "p", "senID": 0, "childList": []}, {"text": ["Also in 3.0.1: Let's say you have two Idle windows open: a script open for editing in one, and Idle's Python Shell window.", "I have found that if you close the shell window and then immediately try to run the script, it will give that error when it tries to re-open the shell - but not if you wait a bit in between to let Idle do whatever connection clean up it needs to do."], "childNum": 0, "tag": "p", "senID": 1, "childList": []}, {"text": ["Worse bugs I have found (again, in v3.0.1- not sure if this would happen in the 2.x versions):\nI had a long script - getting up towards 9k lines - and once it got to a certain size, doing \"save as\" on it would crash Idle.", "I am not sure what the exact threshold was for size - but before that, I would also get some intermittent \"save as\" crashes that seemed to depend on what else I had going on - other Idle windows, how much output was in the shell window perhaps - stuff like that.", "It can crash and you will lose unsaved work."], "childNum": 0, "tag": "p", "senID": 2, "childList": []}, {"text": ["Also - one thing I commonly do is have a scratch window open where I cut and paste bits of code in various stages of validity, write notes to myself, etc - so not a valid python script, but I sometimes save these so I can come back to them.", "I have one such file that will crash Idle every time I try to open it - and I lost unsaved work the first time.", "(FYI: Other editors including PythonWin 2.5.2 have no problem opening the file."], "childNum": 0, "tag": "p", "senID": 3, "childList": []}], [{"text": ["Can you be more specific by providing a short code sample?"], "childNum": 0, "tag": "p", "senID": 0, "childList": []}, {"text": ["IDLE has some threading issues.", "So the first thing to debug your problem would be to print some simple stuff in your subprocess.", "Thereby you will see whether it is a network or threading related issue."], "childNum": 0, "tag": "p", "senID": 1, "childList": []}], [{"text": ["If it look like truly random behavior than it could be a multi-cpu/core issue.", "You could try to set the interpreter affinity to a fixed cpu and see if this issue still comes up."], "childNum": 0, "tag": "p", "senID": 0, "childList": []}, {"text": ["Google for something like: imagecfg process affinity\nFor more information about that."], "childNum": 0, "tag": "p", "senID": 1, "childList": []}], [{"text": ["Or..you could forget IDLE and try IPython instead.", "It may not exhibit the same error at all.", "I've never had a problem with it.", "You get some cool functionality with it that IDLE doesn't have.", "I find it very useful when working with Python."], "childNum": 1, "tag": "p", "senID": 0, "childList": [{"text": "IPython", "tag": "a", "pos": 0, "childList": [], "childNum": 0, "href": "http://ipython.scipy.org/moin/"}]}], [{"text": ["Simple.", "Just cut all files with .py extension, paste them in a place different from the os path, one of the files is causing such error.", "Run the IDLE again."], "childNum": 0, "tag": "p", "senID": 0, "childList": []}]]